### PR TITLE
Added VS2022 Support

### PR DESCRIPTION
**Pull request by shmuelie**

### CODE REVIEW

**Comment by nzbart** [comment]
It'd be great if this could be merged and published...

**Comment by nzbart** [comment]
I worked around this problem with the following in my profile instead of `vs2022`:

```powershell
& (Import-Module PSVSEnv -PassThru) { Set-VSEnvVSWhere '[17.0,18.0)' 'Common7\Tools\VsDevCmd.bat' }
```

**Comment by ecsousa** [comment]
Thank you!! I'll publish this to PSGallery

**Comment by bartecargo** [comment]
Thanks, @shmuelie and @ecsousa!

**Pull request merged**
